version: '3.8'

services:
  mysql:
    container_name: catalog_admin_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: catalog_admin_db
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    networks:
      - catalog_admin_network

  adminer:
    container_name: catalog_admin_adminer
    image: adminer:latest
    restart: always
    ports:
      - "2000:8080"
    networks:
      - catalog_admin_network

networks:
  catalog_admin_network: